"""initialize tables

Revision ID: 6f7ba194c91e
Revises:
Create Date: 2025-11-24 16:07:41.158557

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f7ba194c91e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "measurements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column("bus_id", sa.String(), nullable=True),
        sa.Column("p_kw", sa.Float(), nullable=True),
        sa.Column("q_kvar", sa.Float(), nullable=True),
        sa.Column("v_pu", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_measurements_bus_id"), "measurements", ["bus_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_measurements_bus_id"), table_name="measurements")
    op.drop_table("measurements")
    # ### end Alembic commands ###
